<script lang="ts" setup></script>

<template>
    <div>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
    </div>
</template>

<style lang="scss" scoped></style>